version: '3.8'
services:
  app:
    depends_on:
      - mongodb
    container_name: Transformer-Chatbot-be
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - transformer-chatbot-db:/data/db
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"

  # mongo-express:
  #   image: mongo-express
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   environment:
  #       - ME_CONFIG_MONGODB_SERVER=mongodb
  #       - ME_CONFIG_MONGODB_PORT=27017
  #       - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #       - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #       - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #       - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #       - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
  #       - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  #   depends_on:
  #       - mongodb
  #   ports:
  #     - "8081:8081"

volumes:
  transformer-chatbot-db:
    driver: local